#registro_eventos_core_index:
#    path:     /
#    defaults: { _controller: RegistroEventosCoreBundle:Default:index }

registro_eventos_core_administracion:
    path:     /administracion
    defaults: { _controller: RegistroEventosCoreBundle:Administracion:index }

registro_eventos_core_administracion_usuarios:
    path:     /administracion/usuarios
    defaults: { _controller: RegistroEventosCoreBundle:Administracion:listarUsuarios }

registro_eventos_core_administracion_usuarios_alta:
    path:     /administracion/usuarios/nuevo
    defaults: { _controller: RegistroEventosCoreBundle:Administracion:crearUsuario }

registro_eventos_core_administracion_usuarios_baja:
    path:     /administracion/usuarios/eliminar
    defaults: { _controller: RegistroEventosCoreBundle:Administracion:eliminarUsuario }

registro_eventos_core_administracion_usuarios_modificacion:
    path:     /administracion/usuarios/modificar
    defaults: { _controller: RegistroEventosCoreBundle:Administracion:modificarUsuario }

registro_eventos_core_supervision:
    path:     /supervision
    defaults: { _controller: RegistroEventosCoreBundle:Supervision:index }

RegistroEventosCoreBundle_agenda:
    resource: "@RegistroEventosCoreBundle/Resources/config/routing/contacto.yml"
    prefix:   /agenda

RegistroEventosCoreBundle_eventos:
    resource: "@RegistroEventosCoreBundle/Resources/config/routing/evento.yml"
    prefix:   /

RegistroEventosCoreBundle_tipos_eventos:
    resource: "@RegistroEventosCoreBundle/Resources/config/routing/tipoevento.yml"
    prefix:   /tipos_eventos

RegistroEventosCoreBundle_usuarios:
    resource: "@RegistroEventosCoreBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuarios


