registro_eventos_core_index:
    path:     /
    defaults: { _controller: RegistroEventosCoreBundle:Default:index }

registro_eventos_core_administracion:
    path:     /administracion
    defaults: { _controller: RegistroEventosCoreBundle:Administracion:index }

registro_eventos_core_administracion_usuarios:
    path:     /administracion/usuarios
    defaults: { _controller: RegistroEventosCoreBundle:Administracion:usuarios }

registro_eventos_core_administracion:
    path:     /supervision
    defaults: { _controller: RegistroEventosCoreBundle:Supervision:index }
