registro_eventos_core_administracion:
    path:     /administracion
    defaults: { _controller: RegistroEventosCoreBundle:Administracion:index }

RegistroEventosCoreBundle_agenda:
    resource: "@RegistroEventosCoreBundle/Resources/config/routing/contacto.yml"
    prefix:   /agenda

RegistroEventosCoreBundle_eventos:
    resource: "@RegistroEventosCoreBundle/Resources/config/routing/evento.yml"
    prefix:   /

RegistroEventosCoreBundle_tipos_eventos:
    resource: "@RegistroEventosCoreBundle/Resources/config/routing/tipoevento.yml"
    prefix:   /administracion/tipos_eventos

RegistroEventosCoreBundle_usuarios:
    resource: "@RegistroEventosCoreBundle/Resources/config/routing/usuario.yml"
    prefix:   /administracion/usuarios


