parameters:
#    registro_eventos_core.example.class: RegistroEventos\CoreBundle\Example

services:
#    registro_eventos_core.example:
#        class: %registro_eventos_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
