parameters:
#    registro_eventos_core.example.class: RegistroEventos\CoreBundle\Example

services:
#    registro_eventos_core.example:
#        class: %registro_eventos_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    registro_eventos_core.registration.form.type:
        class: RegistroEventos\CoreBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: registro_eventos_core_registration }