registro_eventos_core:
    resource: "@RegistroEventosCoreBundle/Resources/config/routing.yml"
    prefix:   /

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#RegistroEventosCoreBundle_administracion_tipos:
#        resource: "@RegistroEventosCoreBundle/Resources/config/routing/tipoevento.yml"
#        prefix:   /administracion/tipos