registro_eventos_core:
    resource: "@RegistroEventosCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_all:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"