security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPERVISOR: ROLE_USER
        ROLE_INTENDENTE: ROLE_USER
        ROLE_ADMINISTRADOR: [ROLE_SUPERVISOR]

    providers:
        
        fos_userbundle:
            id: fos_user.user_provider.username
    
#    encoders:
#        Symfony\Component\Security\Core\User\User:
#                algorithm:   sha1
#                iterations: 1
#                encode_as_base64: false

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: registro_eventos_core.success_handler
            logout:       true
            anonymous:    true
            
    
    
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administracion, roles: ROLE_ADMINISTRADOR }
        - { path: ^/supervision, roles: ROLE_SUPERVISOR }
        - { path: ^/, roles: ROLE_INTENDENTE }

