<?php

namespace RegistroEventos\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleRepository extends EntityRepository
{

    public function listarPara($evento)
    {
        return $this->createQueryBuilder('d')
                ->select('d')
                ->where('d.evento = :idEvento')
                ->setParameter('idEvento', $evento->getId())
                ->getQuery()->getResult();
    }

}
