<?php

namespace RegistroEventos\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends EntityRepository
{
    private function buscarEventosActivosConEstado($estado){
        return $this->createQueryBuilder('e')
                ->select('e')
                ->where('e.rectificacion IS NULL')
                ->andWhere('e.estado = :estado')->setParameter('estado', $estado)
                ->orderBy('e.fechaEvento', 'DESC')
                ->getQuery()
                ->getResult();
    }
    public function buscarEventosAbiertos() {
        return $this->buscarEventosActivosConEstado(TRUE);
    }
    
    public function buscarEventosCerrados() {
        return $this->buscarEventosActivosConEstado(FALSE);
    }
}
