<?php

namespace RegistroEventos\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEventoRepository extends EntityRepository
{
	public function listarTiposEventosActivos(){
		return $this->createQueryBuilder('t')
			->select('t')
			->where('t.baja = :baja')->setParameter('baja',FALSE)
			->getQuery()->getResult();
	}
}
