<?php

namespace RegistroEventos\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function listar() {
            return $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.baja = FALSE')
            ->getQuery()
            ->getResult();
	}
}
