<?php

namespace RegistroEventos\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function listar() {
            return $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.baja = FALSE')
            ->getQuery()
            ->getResult();
	}
	public function estadisticaEventosDelUsuario(){
            return $this->createQueryBuilder('u')
            ->addSelect('u.id, u.nombre')
            ->addSelect('count(e) as eventos')
            ->leftJoin('u.eventos', 'e')
            ->groupBy('u.id')
            ->getQuery()
            ->getResult();			
	}
	public function estadisticaRectificacionesDelUsuario(){
            return $this->createQueryBuilder('u')
            ->addSelect('u.id, u.nombre')
            ->addSelect('count(e) as eventos')
            ->leftJoin('u.eventos', 'e')
            ->where('e.rectificacion is not null')
            ->groupBy('u.id')
            ->getQuery()
            ->getResult();			
	}	
}
