<?php

namespace RegistroEventos\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function listar() {
		return $this->getEntityManager()
		->createQueryBuilder()
		->select('u')
		->from('RegistroEventosCoreBundle:Usuario','u')
		->getQuery()
		->getResult();
	}
}
