eventos:
    path:     /
    defaults: { _controller: "RegistroEventosCoreBundle:Evento:index" }
    options:
        expose: true

eventos_crear:
    path:     /crear
    defaults: { _controller: "RegistroEventosCoreBundle:Evento:crear" }
    requirements: { _method: post }

eventos_rectificacion_nueva:
    path:     /rectificacion_nueva
    defaults: { _controller: "RegistroEventosCoreBundle:Evento:nuevaRectificacion" }
    options:
        expose: true

eventos_rectificacion_crear:
    path:     /rectificacion_crear
    defaults: { _controller: "RegistroEventosCoreBundle:Evento:crearRectificacion" }
    requirements: { _method: post }
    options:
        expose: true

eventos_abrir:
    path:     /{id}/abrir
    defaults: { _controller: "RegistroEventosCoreBundle:Evento:abrirEvento" }

eventos_cerrar:
    path:     /{id}/cerrar
    defaults: { _controller: "RegistroEventosCoreBundle:Evento:cerrarEvento" }
    
eventos_detalle:
    path:     /{id}/detalle
    defaults: { _controller: "RegistroEventosCoreBundle:Evento:detalleEvento" }
    options:
        expose: true
        
eventos_detalle_crear:
    path:     /detalle_crear
    defaults: { _controller: "RegistroEventosCoreBundle:Evento:crearDetalleEvento" }
    options:
        expose: true
        
eventos_busqueda:
    path:     /busqueda
    defaults: { _controller: "RegistroEventosCoreBundle:Evento:busqueda" }
    
eventos_supervision:
    path:     /supervision
    defaults: { _controller: "RegistroEventosCoreBundle:Evento:supervision" }