tipos_eventos:
    path:     /
    defaults: { _controller: "RegistroEventosCoreBundle:TipoEvento:index" }

tipos_eventos_show:
    path:     /{id}/show
    defaults: { _controller: "RegistroEventosCoreBundle:TipoEvento:show" }

tipos_eventos_new:
    path:     /new
    defaults: { _controller: "RegistroEventosCoreBundle:TipoEvento:new" }

tipos_eventos_create:
    path:     /create
    defaults: { _controller: "RegistroEventosCoreBundle:TipoEvento:create" }
    requirements: { _method: post }

tipos_eventos_edit:
    path:     /{id}/edit
    defaults: { _controller: "RegistroEventosCoreBundle:TipoEvento:edit" }

tipos_eventos_update:
    path:     /{id}/update
    defaults: { _controller: "RegistroEventosCoreBundle:TipoEvento:update" }
    requirements: { _method: post|put }

tipos_eventos_delete:
    path:     /{id}/delete
    defaults: { _controller: "RegistroEventosCoreBundle:TipoEvento:delete" }
    requirements: { _method: post|delete }
